### PR TITLE
Fix the addon purchase issues

### PR DESCRIPTION
**Pull request by NorthIsUp**

### CODE REVIEW

**Comment by NorthIsUp** [comment]
fixes #22

**Comment by CarlNelson** [comment]
@NorthIsUp You missed some functionality when you rewrote the feature instead of rebasing @NicoleZuckerman's code.

- [ ] Does not show a call to action on the Profile page ticket to 'Purchase Add-Ons'
- [ ] Should show a Total Amount - Amount Paid with a Your Total on the check-out page.

**Comment by NorthIsUp** [comment]
@CarlNelson can you provide a screenshot of the issue for "Should show a Total Amount…"

**Comment by CarlNelson** [comment]
I can't since I can't seem to get @NicoleZuckerman's original work up and running to take a screenshot of what it should look like but please look at this [commit](https://github.com/SugarPushCode/FocusOnLindy/commit/9a64f86364405448a542fd8335d000ce733cea92) and the markup changes for ticket_card.html and profile.html in that commit.

**Comment by CarlNelson** [comment]
@NorthIsUp did you re-implement the features that were missed in your rewrite?

**Comment by NorthIsUp** [comment]
Not yet

**Comment by NorthIsUp** [comment]
I was partying all weekend. I'll do them this week

**Pull request merged**
