### PR TITLE
change add on description to show they are sold out when sold out

### PR DESCRIPTION
**Pull request by NicoleZuckerman**
@CarlNelson

### CODE REVIEW

**Comment by NicoleZuckerman** [comment]
@NorthIsUp FYI we did this so there is some visual representation on the page of WHY you can't select a thing.

**Comment by CarlNelson** [comment]
LGTM. Runs fine locally for me.

**Comment by NorthIsUp** [comment]
Lgtm

**Comment by NicoleZuckerman** [comment]
@NorthIsUp Can you and @CarlNelson merge this when you get in? Front desk check-in is probably still in peak time and I don't want to screw them up with a deploy right now.

**Pull request merged**
